openapi: 3.1.0
info:
  title: Inopsio InoSec Core Service API
  version: 1.0.0
  description: Core cybersecurity platform API for threat detection and incident management

servers:
  - url: https://api.inopsio.com/v1/inosec/core
    description: Production InoSec Core API

tags:
  - name: Threats
    description: Threat detection and management
  - name: Incidents
    description: Security incident management
  - name: Analytics
    description: Security analytics

paths:
  /threats:
    get:
      summary: List detected threats
      tags: [Threats]
      parameters:
        - name: severity
          in: query
          schema:
            type: string
            enum: [critical, high, medium, low]
      responses:
        "200":
          description: List of threats

  /incidents:
    get:
      summary: List security incidents
      tags: [Incidents]
      responses:
        "200":
          description: List of incidents

    post:
      summary: Create security incident
      tags: [Incidents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIncidentRequest'
      responses:
        "201":
          description: Incident created successfully

components:
  schemas:
    CreateIncidentRequest:
      type: object
      required:
        - title
        - severity
      properties:
        title:
          type: string
        severity:
          type: string
          enum: [critical, high, medium, low]
        description:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
