version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "inopsio-dev-team"
    assignees:
      - "inopsio-dev-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # Enable version updates for npm in frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "inopsio-frontend-team"
    assignees:
      - "inopsio-frontend-team"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"

  # Enable version updates for npm in backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "inopsio-backend-team"
    assignees:
      - "inopsio-backend-team"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "javascript"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "inopsio-devops-team"
    assignees:
      - "inopsio-devops-team"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "inopsio-devops-team"
    assignees:
      - "inopsio-devops-team"
    commit-message:
      prefix: "deps(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "ci-cd"
      - "github-actions"

  # Enable version updates for Terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "inopsio-devops-team"
    assignees:
      - "inopsio-devops-team"
    commit-message:
      prefix: "deps(terraform)"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"

  # Enable version updates for Python (if applicable)
  - package-ecosystem: "pip"
    directory: "/backend/ai-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "inopsio-ai-team"
    assignees:
      - "inopsio-ai-team"
    commit-message:
      prefix: "deps(ai)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "ai-ml"
