# Prometheus configuration for AI Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ai-service-rules.yml"

scrape_configs:
  - job_name: 'ai-service'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'ai-service-health'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'ai-service-ml-metrics'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/ml/metrics'
    scrape_interval: 10s
