name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci
      
      - name: Run linting
        run: |
          npm run lint
          cd frontend && npm run lint
          cd ../backend && npm run lint
      
      - name: Run unit tests
        run: |
          npm run test:unit
          cd frontend && npm run test:unit
          cd ../backend && npm run test:unit
      
      - name: Run integration tests
        run: |
          npm run test:integration
          cd frontend && npm run test:integration
          cd ../backend && npm run test:integration
      
      - name: Run E2E tests
        run: |
          npm run test:e2e
          cd frontend && npm run test:e2e
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            test-results/
            coverage/
            frontend/test-results/
            frontend/coverage/
            backend/test-results/
            backend/coverage/
